### ISSUE TITLE
Error importing WpApiModule

### ISSUE THREAD

**Issue by klihelp** [shprink/wp-api-angular#19]
`import {  WpApiModule } from 'wp-api-angular';`

`ERROR in Error encountered resolving symbol values statically. Calling function 'WpApiModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/mac/../src/app/app.module.ts`

ref: https://github.com/angular/angular-cli/issues/3707

**Comment by klihelp** [comment]
https://github.com/angular/angular-cli/issues/3707

**Comment by klihelp** [comment]
Some info:
https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.e7eqfyvh1

**Comment by klihelp** [comment]
Manual editing fix in wp-api-angular.d.ts:

ps - from `npm install wp-api-angular` the project looks older than at develop branch ..

```
export declare class WpApiModule {
    // static initializeApp(config: WpApiAppConfig): ModuleWithProviders;
    static initializeApp(config: WpApiAppConfig): ModuleWithProviders {
    	return {
			ngModule: WpApiModule,
			providers: [
			]
		}
	}
}
```

**Comment by klihelp** [comment]
The above changes works with angular JIT compilation, but not with AOT.
```
[at-loader] Checking finished with 1 errors
[at-loader] node_modules/wp-api-angular/wp-api-angular.d.ts:22:71 
    An implementation cannot be declared in ambient contexts. 
```

**Comment by shprink** [comment]
checking, thanks for reporting

**Comment by shprink** [comment]
I released beta3, it should fix the AoT. Upgrade, try and let me know :)

**Comment by klihelp** [comment]
Still the same error:

`Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Error encountered resolving symbol values statically. Calling function 'WpApiModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ..`

**Comment by shprink** [comment]
Are you sure you have beta3?

I can now run the following command:

```
$ ng build --aot
Hash: 6a207f80a1a31c8def16
Time: 11483ms
chunk    {0} main.bundle.js, main.bundle.map (main) 61.6 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.77 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.02 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
```

before beta3 I had:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'WpApiModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/julienrenaux/Sites/wp-api-angularjs/aot/src/app/app.module.ts, resolving symbol AppModule in /Users/julienrenaux/Sites/wp-api-angularjs/aot/src/app/app.module.ts
```

**Comment by klihelp** [comment]
yes, I have manually checked  package.json.

I use with this webpack based starter project:
https://github.com/Websitescity/ng2-f6-starter

**Comment by shprink** [comment]
ok thanks for sharing, I am going to try on this too!

**Comment by shprink** [comment]
I can reproduce, this will help me fixing it thanks!

**Comment by shprink** [comment]
should be fine with beta4. please try and let me know

**Comment by shprink** [comment]
@klihelp can we close?

**Comment by klihelp** [comment]
I am getting  and error on 3.0.0-beta4, issue #20

**Comment by shprink** [comment]
beta5 now works with Angular CLI but not on you startup project and Ionic CLI. On it..

**Comment by shprink** [comment]
well actually it works on your project too. please confirm

**Comment by shprink** [comment]
beta6 works on all cases. please try

**Comment by klihelp** [comment]
Thanks for your project. All works now.

**Comment by shprink** [comment]
Finally!

**Comment by klihelp** [comment]
Just for a reading mention
https://github.com/UltimateAngular/rollup-plugin-aot
